#ifndef CURSOR_H
    #define CURSOR_H

    #include "user_interface.h"

    static const char *cursor_arrow[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ffffff",
      "  c None",
      /* pixels */
      "X                               ",
      "XX                              ",
      "X.X                             ",
      "X..X                            ",
      "X...X                           ",
      "X....X                          ",
      "X.....X                         ",
      "X......X                        ",
      "X.......X                       ",
      "X........X                      ",
      "X.....XXXXX                     ",
      "X..X..X                         ",
      "X.X X..X                        ",
      "XX  X..X                        ",
      "X    X..X                       ",
      "     X..X                       ",
      "      X..X                      ",
      "      X..X                      ",
      "       XX                       ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "0,0"
    };

    /* XPM */
    static const char *cursor_cross[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ffffff",
      "  c None",
      /* pixels */
      "        X                       ",
      "       X.X                      ",
      "       X.X                      ",
      "       X.X                      ",
      "       X.X                      ",
      "       X.X                      ",
      "       X.X                      ",
      " XXXXXX X XXXXXX                ",
      "X......X X......X               ",
      " XXXXXX X XXXXXX                ",
      "       X.X                      ",
      "       X.X                      ",
      "       X.X                      ",
      "       X.X                      ",
      "       X.X                      ",
      "       X.X                      ",
      "        X                       ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "0,0"
    };

    static const char *cursor_arrow_VRT[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ffffff",
      "  c None",
      /* pixels */
      "X                               ",
      "XX                              ",
      "X.X                             ",
      "X..X                            ",
      "X...X                           ",
      "X....X                          ",
      "X.....X                         ",
      "X......X                        ",
      "X.......X                       ",
      "X........X                      ",
      "X.....XXXXX                     ",
      "X..X..X                         ",
      "X.X X..X                        ",
      "XX  X..X                        ",
      "X    X..X                       ",
      "     X..X                       ",
      "      X..X        XX            ",
      "      X..X       X..X           ",
      "       XX       X....X          ",
      "               X......X         ",
      "               XXX..XXX         ",
      "                 X..X           ",
      "                 X..X           ",
      "                 X..X           ",
      "                 X..X           ",
      "                 X..X           ",
      "                 X..X           ",
      "               XXX  XXX         ",
      "               X......X         ",
      "                X....X          ",
      "                 X..X           ",
      "                  XX            ",
      "0,0"
    };

    static const char *cursor_arrow_HRZ[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ffffff",
      "  c None",
      /* pixels */
      "X                               ",
      "XX                              ",
      "X.X                             ",
      "X..X                            ",
      "X...X                           ",
      "X....X                          ",
      "X.....X                         ",
      "X......X                        ",
      "X.......X                       ",
      "X........X                      ",
      "X.....XXXXX                     ",
      "X..X..X                         ",
      "X.X X..X                        ",
      "XX  X..X                        ",
      "X    X..X                       ",
      "     X..X                       ",
      "      X..X                      ",
      "      X..X                      ",
      "       XX                       ",
      "                                ",
      "              XX      XX        ",
      "             X.X      X.X       ",
      "            X..XXXXXXXX..X      ",
      "           X..............X     ",
      "           X..............X     ",
      "            X..XXXXXXXX..X      ",
      "             X.X      X.X       ",
      "              XX      XX        ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "0,0"
    };

    static const char *cursor_arrow_CRX[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ffffff",
      "  c None",
      /* pixels */
      "X                               ",
      "XX                              ",
      "X.X                             ",
      "X..X                            ",
      "X...X                           ",
      "X....X                          ",
      "X.....X                         ",
      "X......X                        ",
      "X.......X                       ",
      "X........X                      ",
      "X.....XXXXX                     ",
      "X..X..X                         ",
      "X.X X..X                        ",
      "XX  X..X                        ",
      "X    X..X                       ",
      "     X..X              X        ",
      "      X..X            X.X       ",
      "      X..X            X.X       ",
      "       XX             X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                XXXXXX X XXXXXX ",
      "               X......X X......X",
      "                XXXXXX X XXXXXX ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                       X        ",
      "0,0"
    };

    static const char *cursor_arrow_cornA[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ffffff",
      "  c None",
      /* pixels */
      "X                               ",
      "XX                              ",
      "X.X                             ",
      "X..X                            ",
      "X...X                           ",
      "X....X                          ",
      "X.....X                         ",
      "X......X                        ",
      "X.......X                       ",
      "X........X                      ",
      "X.....XXXXX                     ",
      "X..X..X                         ",
      "X.X X..X                        ",
      "XX  X..X                        ",
      "X    X..X                       ",
      "     X..X                       ",
      "      X..X                      ",
      "      X..X                      ",
      "       XX                       ",
      "                                ",
      "                                ",
      "                                ",
      "                       X XXXXXX ",
      "                      X X......X",
      "                       X XXXXXX ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                       X        ",
      "0,0"
    };

    static const char *cursor_arrow_cornB[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ffffff",
      "  c None",
      /* pixels */
      "X                               ",
      "XX                              ",
      "X.X                             ",
      "X..X                            ",
      "X...X                           ",
      "X....X                          ",
      "X.....X                         ",
      "X......X                        ",
      "X.......X                       ",
      "X........X                      ",
      "X.....XXXXX                     ",
      "X..X..X                         ",
      "X.X X..X                        ",
      "XX  X..X                        ",
      "X    X..X                       ",
      "     X..X                       ",
      "      X..X                      ",
      "      X..X                      ",
      "       XX                       ",
      "                                ",
      "                                ",
      "                                ",
      "                XXXXXX X        ",
      "               X......X X       ",
      "                XXXXXX X        ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                       X        ",
      "0,0"
    };

    static const char *cursor_arrow_cornC[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ffffff",
      "  c None",
      /* pixels */
      "X                               ",
      "XX                              ",
      "X.X                             ",
      "X..X                            ",
      "X...X                           ",
      "X....X                          ",
      "X.....X                         ",
      "X......X                        ",
      "X.......X                       ",
      "X........X                      ",
      "X.....XXXXX                     ",
      "X..X..X                         ",
      "X.X X..X                        ",
      "XX  X..X                        ",
      "X    X..X                       ",
      "     X..X              X        ",
      "      X..X            X.X       ",
      "      X..X            X.X       ",
      "       XX             X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                       X XXXXXX ",
      "                      X X......X",
      "                       X XXXXXX ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "0,0"
    };

    static const char *cursor_arrow_cornD[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ffffff",
      "  c None",
      /* pixels */
      "X                               ",
      "XX                              ",
      "X.X                             ",
      "X..X                            ",
      "X...X                           ",
      "X....X                          ",
      "X.....X                         ",
      "X......X                        ",
      "X.......X                       ",
      "X........X                      ",
      "X.....XXXXX                     ",
      "X..X..X                         ",
      "X.X X..X                        ",
      "XX  X..X                        ",
      "X    X..X                       ",
      "     X..X              X        ",
      "      X..X            X.X       ",
      "      X..X            X.X       ",
      "       XX             X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                XXXXXX X        ",
      "               X......X X       ",
      "                XXXXXX X        ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "0,0"
    };

    /* XPM */
    static const char *cursor_cross_shift[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ffffff",
      "  c None",
      /* pixels */
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                       X        ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                XXXXXX X XXXXXX ",
      "               X......X X......X",
      "                XXXXXX X XXXXXX ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                      X.X       ",
      "                       X        ",
      "0,0"
    };

    static const char *dbg_cursor_arrow[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ff0000",
      "  c None",
      /* pixels */
      "X                               ",
      "XX                              ",
      "X.X                             ",
      "X..X                            ",
      "X...X                           ",
      "X....X                          ",
      "X.....X                         ",
      "X......X                        ",
      "X.......X                       ",
      "X........X                      ",
      "X.....XXXXX                     ",
      "X..X..X                         ",
      "X.X X..X                        ",
      "XX  X..X                        ",
      "X    X..X                       ",
      "     X..X                       ",
      "      X..X                      ",
      "      X..X                      ",
      "       XX        ..             ",
      "                .XX.            ",
      "               .XXXX.           ",
      "               .XXXX.           ",
      "               .XXXX.           ",
      "                .XX.            ",
      "                .XX.            ",
      "                 ..             ",
      "                .XX.            ",
      "                .XX.            ",
      "                 ..             ",
      "                                ",
      "                                ",
      "                                ",
      "0,0"
    };

    static const char *cursor_arrow_shift[] = {
      /* width height num_colors chars_per_pixel */
      "    32    32        3            1",
      /* colors */
      "X c #000000",
      ". c #ffffff",
      "  c None",
      /* pixels */
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "        X                       ",
      "        XX                      ",
      "        X.X                     ",
      "        X..X                    ",
      "        X...X                   ",
      "        X....X                  ",
      "        X.....X                 ",
      "        X......X                ",
      "        X.......X               ",
      "        X........X              ",
      "        X.....XXXXX             ",
      "        X..X..X                 ",
      "        X.X X..X                ",
      "        XX  X..X                ",
      "        X    X..X               ",
      "             X..X               ",
      "              X..X              ",
      "              X..X              ",
      "               XX               ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "                                ",
      "0,0"
    };

#endif // CURSOR_H
